# Generated by Django 4.2.7 on 2026-01-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurant_category_restaurant_product_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_note',
            field=models.TextField(blank=True, help_text='Specific delivery instructions for this restaurant'),
        ),
    ]
