# Generated by Django 6.0 on 2026-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurant_delivery_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
