# Generated by Django 6.0 on 2026-01-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurant_cover_image_restaurant_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
    ]
