# Generated by Django 6.0 on 2026-01-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_restaurant_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_featured_campaign',
            field=models.BooleanField(default=False, help_text='Show as Hero Campaign on Home Screen'),
        ),
    ]
