# Generated by Django 6.0 on 2026-01-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurant_is_featured_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='paybill_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='till_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
