# Generated by Django 6.0 on 2026-01-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restaurant_bank_account_number_restaurant_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping fee for this product (0 for free)', max_digits=10),
        ),
    ]
