# Generated by Django 6.0 on 2026-01-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='campaign_image',
            field=models.ImageField(blank=True, help_text='Image for Hero Campaign Slider', null=True, upload_to='restaurants/campaigns/'),
        ),
    ]
