# Generated by Django 6.0 on 2026-01-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_restaurant_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Show in Hot Products section'),
        ),
    ]
