# Generated by Django 6.0 on 2026-01-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='is_highlight',
            field=models.BooleanField(default=False, help_text='Show this reel first'),
        ),
    ]
