# Generated by Django 6.0 on 2026-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reel_is_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_mode',
            field=models.CharField(choices=[('FREE', 'Free Delivery'), ('FIXED', 'Fixed Delivery Fee'), ('CONFIRM', 'Confirm via Call/WhatsApp')], default='CONFIRM', help_text='Select how delivery fee is calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fixed_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Required if Delivery Mode is 'Fixed'", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Order amount above which delivery is free (optional for Fixed mode)', max_digits=10, null=True),
        ),
    ]
