# Generated by Django 6.0 on 2026-02-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_restaurant_delivery_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_fee',
        ),
    ]
